### ISSUE TITLE
InvalidOperation on Fireblocks endpoint

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/emergency-response#36]
Running into an issue on the fireblocks endpoint I have not been able to resolve. This is the stacktrace I am receiving:

`Internal Server Error: /fireblocks
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "/home/vagrant/proj/emergency_response_api/emergency_data/data/views.py", line 45, in fireblock_list
    return Response(serializedFireblocks.data)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/serializers.py", line 725, in data
    ret = super(ListSerializer, self).data
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/serializers.py", line 643, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/serializers.py", line 643, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/serializers.py", line 496, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/fields.py", line 1054, in to_representation
    quantized = self.quantize(value)
  File "/home/vagrant/miniconda3/envs/cvdjango/lib/python3.5/site-packages/rest_framework/fields.py", line 1075, in quantize
    context=context
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
[24/Jan/2017 19:13:11] "GET /fireblocks HTTP/1.1" 500 136339`

**Comment by BrianHGrant** [comment]
Opening new issue for specific questions
